import json

with open(r'D:\Projects\ireb_cpre_fl\validations\2026-05-27_v3.3.0\downloads\glossary_terms_raw.json', 'r', encoding='utf-8') as f:
    terms = json.load(f)

# Build the Vue script section with all terms
lines = []
lines.append('<script setup>')
lines.append("import { ref, computed } from 'vue'")
lines.append('')
lines.append("const searchTerm = ref('')")
lines.append('')
lines.append('const terms = [')
for t in terms:
    term_escaped = t['term'].replace("'", "\\'")
    defn_escaped = t['definition'].replace("'", "\\'")
    lines.append(f"  {{ term: '{term_escaped}', definition: '{defn_escaped}' }},")
lines.append(']')
lines.append('')
lines.append('const filteredTerms = computed(() => {')
lines.append('  if (!searchTerm.value) return terms')
lines.append('  const q = searchTerm.value.toLowerCase()')
lines.append('  return terms.filter(')
lines.append("    t => t.term.toLowerCase().includes(q) || t.definition.toLowerCase().includes(q)")
lines.append('  )')
lines.append('})')
lines.append('</script>')
lines.append('')
lines.append('# Glossary (Syllabus v3.3.0)')
lines.append('')
lines.append('::: info Source')
lines.append('Verbatim definitions from the **IREB CPRE Glossary v2.2.0** (October 2025) by Martin Glinz.')
lines.append('[Download official glossary](https://cpre.ireb.org/en/downloads-and-resources/downloads)')
lines.append(':::')
lines.append('')
lines.append(f'A searchable reference of {len(terms)} terms from the official IREB CPRE glossary.')
lines.append('')
lines.append('<div style="margin: 1.5rem 0;">')
lines.append('  <input')
lines.append('    v-model="searchTerm"')
lines.append('    type="text"')
lines.append('    placeholder="Search terms..."')
lines.append('    style="')
lines.append('      width: 100%;')
lines.append('      padding: 0.6rem 1rem;')
lines.append('      border: 1px solid var(--vp-c-divider);')
lines.append('      border-radius: 8px;')
lines.append('      background: var(--vp-c-bg);')
lines.append('      color: var(--vp-c-text-1);')
lines.append('      font-size: 1rem;')
lines.append('      outline: none;')
lines.append('    "')
lines.append('  />')
lines.append('</div>')
lines.append('')
lines.append('<div v-if="filteredTerms.length === 0" style="color: var(--vp-c-text-2); padding: 1rem;">')
lines.append('  No terms match your search.')
lines.append('</div>')
lines.append('')
lines.append('<div v-for="t in filteredTerms" :key="t.term" style="margin-bottom: 1rem; padding: 0.75rem 1rem; border: 1px solid var(--vp-c-divider); border-radius: 8px; background: var(--vp-c-bg-soft);">')
lines.append('  <strong>{{ t.term }}</strong>')
lines.append('  <p style="margin: 0.25rem 0 0 0; color: var(--vp-c-text-2); font-size: 0.95em;">{{ t.definition }}</p>')
lines.append('</div>')

output = '\n'.join(lines)

with open(r'D:\Projects\ireb_cpre_fl\docs\v3\glossary.md', 'w', encoding='utf-8') as f:
    f.write(output)

print(f'Generated glossary with {len(terms)} terms')
